[package]
name = "mqttc"
version = "0.1.0"
authors = ["Maksim V. <inre.storm@gmail.com>"]
description = "Mqttc is a client for the MQTT protocol."
repository = "https://github.com/inre/rust-mq"
license = "MIT"

[dependencies]
log = "0.3"
rand = "0.3"
byteorder = "0.4"
mqtt3 = "0.1"
netopt = "0.1"

[dev-dependencies]
env_logger = "0.3"
